"use client";
import { useState } from "react";
import { ArrowLeft, ChevronDown, ChevronUp, Eye, ImagePlus, LogOut, Plus, Save, Settings, ShoppingBag, Trash2 } from "lucide-react";
import type { Product, ProductOption, SiteSettings } from "@/lib/defaults";

export default function AdminPanel({authorized,initial}:{authorized:boolean;initial:{settings:SiteSettings;products:Product[]}|null}){
 const [logged,setLogged]=useState(authorized);const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const [settings,setSettings]=useState(initial?.settings);const [products,setProducts]=useState(initial?.products||[]);const [tab,setTab]=useState<"products"|"settings">("products");const [open,setOpen]=useState("");const [saved,setSaved]=useState("");
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok)location.reload();else setError("Грешна парола");setBusy(false)};
 if(!logged)return <main className="admin-login"><form onSubmit={login}><div className="admin-mark">SO</div><h1>Админ панел</h1><p>Влез, за да управляваш магазина.</p><label>Парола<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></label>{error&&<div className="admin-error">{error}</div>}<button disabled={busy}>{busy?"Проверка…":"Вход"}</button><a href="/"><ArrowLeft/> Към сайта</a></form></main>;
 if(!settings)return null;
 const patchProduct=(id:string,patch:Partial<Product>)=>setProducts(products.map(p=>p.id===id?{...p,...patch}:p));
 const addProduct=()=>{const p:Product={id:crypto.randomUUID(),title:"Нов продукт",category:settings.categories[0]||"Други",description:"",price:0,minQuantity:10,images:[],options:[]};setProducts([...products,p]);setOpen(p.id)};
 const save=async()=>{setBusy(true);setSaved("");const r=await fetch("/api/admin/content",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({settings,products})});setSaved(r.ok?"Промените са запазени":"Възникна грешка");setBusy(false)};
 return <main className="admin-shell"><aside><div className="admin-brand"><span>SO</span><div><strong>{settings.brand}</strong><small>Администрация</small></div></div><button className={tab==="products"?"active":""} onClick={()=>setTab("products")}><ShoppingBag/>Продукти</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}><Settings/>Настройки</button><a href="/" target="_blank"><Eye/>Преглед на сайта</a><button className="logout" onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});setLogged(false)}}><LogOut/>Изход</button></aside><section className="admin-main"><header><div><span>Управление на магазина</span><h1>{tab==="products"?"Продукти и опции":"Настройки на сайта"}</h1></div><button className="save" onClick={save} disabled={busy}><Save/>{busy?"Запазване…":"Запази промените"}</button></header>{saved&&<div className="saved">{saved}</div>}
 {tab==="products"?<div className="admin-content"><div className="admin-heading"><div><h2>Каталог</h2><p>Добавяй продукти, снимки, цени и персонални полета.</p></div><button onClick={addProduct}><Plus/>Нов продукт</button></div>{products.map((p,i)=><div className="editor" key={p.id}><button className="editor-title" onClick={()=>setOpen(open===p.id?"":p.id)}><span className="product-index">{String(i+1).padStart(2,"0")}</span><div><strong>{p.title}</strong><small>{p.category} · от {p.price.toFixed(2)} лв.</small></div>{open===p.id?<ChevronUp/>:<ChevronDown/>}</button>{open===p.id&&<div className="editor-body"><div className="admin-grid"><Field label="Заглавие" value={p.title} onChange={v=>patchProduct(p.id,{title:v})}/><label>Категория<select value={p.category} onChange={e=>patchProduct(p.id,{category:e.target.value})}>{settings.categories.map(c=><option key={c}>{c}</option>)}</select></label><Field label="Цена от (лв.)" type="number" value={String(p.price)} onChange={v=>patchProduct(p.id,{price:Number(v)})}/><Field label="Минимално количество" type="number" value={String(p.minQuantity)} onChange={v=>patchProduct(p.id,{minQuantity:Number(v)})}/><Field label="Етикет" value={p.badge||""} onChange={v=>patchProduct(p.id,{badge:v})}/><label className="wide">Описание<textarea value={p.description} onChange={e=>patchProduct(p.id,{description:e.target.value})}/></label></div><ImageEditor product={p} update={v=>patchProduct(p.id,{images:v})}/><OptionsEditor options={p.options} update={v=>patchProduct(p.id,{options:v})}/><button className="delete" onClick={()=>setProducts(products.filter(x=>x.id!==p.id))}><Trash2/>Изтрий продукта</button></div>}</div>)}</div>:<SettingsEditor value={settings} update={setSettings}/>}</section></main>
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function ImageEditor({product,update}:{product:Product;update:(v:string[])=>void}){const [uploading,setUploading]=useState(false);const upload=async(f:File)=>{setUploading(true);const fd=new FormData();fd.append("file",f);const r=await fetch("/api/admin/upload",{method:"POST",body:fd});if(r.ok)update([...product.images,(await r.json()).url]);setUploading(false)};return <div className="admin-block"><div className="block-head"><div><h3>Снимки и карусел</h3><p>Първата снимка е основна.</p></div><label className="upload-small"><ImagePlus/>{uploading?"Качване…":"Добави снимка"}<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><div className="thumbs">{product.images.map((im,i)=><div key={im}><img src={im} alt=""/><button onClick={()=>update(product.images.filter((_,x)=>x!==i))}><Trash2/></button></div>)}</div></div>}
function OptionsEditor({options,update}:{options:ProductOption[];update:(v:ProductOption[])=>void}){const patch=(i:number,v:Partial<ProductOption>)=>update(options.map((o,x)=>x===i?{...o,...v}:o));return <div className="admin-block"><div className="block-head"><div><h3>Опции за персонализация</h3><p>Изборите се появяват в поръчката на клиента.</p></div><button onClick={()=>update([...options,{id:crypto.randomUUID(),label:"Нова опция",type:"text"}])}><Plus/>Добави опция</button></div><div className="option-list">{options.map((o,i)=><div className="option-row" key={o.id}><input value={o.label} onChange={e=>patch(i,{label:e.target.value})}/><select value={o.type} onChange={e=>patch(i,{type:e.target.value as ProductOption["type"]})}><option value="text">Кратък текст</option><option value="textarea">Свободен текст</option><option value="select">Избор от списък</option><option value="checkbox">Отметка</option></select>{o.type==="select"&&<input placeholder="Опции, разделени със запетая" value={o.choices?.map(c=>c.label).join(", ")||""} onChange={e=>patch(i,{choices:e.target.value.split(",").map(x=>({label:x.trim()})).filter(x=>x.label)})}/>}<label className="tiny-check"><input type="checkbox" checked={!!o.required} onChange={e=>patch(i,{required:e.target.checked})}/>задължително</label><button onClick={()=>update(options.filter((_,x)=>x!==i))}><Trash2/></button></div>)}</div></div>}
function SettingsEditor({value,update}:{value:SiteSettings;update:(v:SiteSettings)=>void}){const p=(k:keyof SiteSettings,v:string|string[])=>update({...value,[k]:v});return <div className="admin-content"><div className="admin-heading"><div><h2>Съдържание и контакти</h2><p>Промените се показват в публичния сайт след запазване.</p></div></div><div className="settings-card"><div className="admin-grid"><Field label="Име на бранда" value={value.brand} onChange={v=>p("brand",v)}/><Field label="Съобщение най-горе" value={value.announcement} onChange={v=>p("announcement",v)}/><label className="wide">Главно заглавие<textarea value={value.headline} onChange={e=>p("headline",e.target.value)}/></label><label className="wide">Кратко представяне<textarea value={value.intro} onChange={e=>p("intro",e.target.value)}/></label><label className="wide">Текст „За нас“<textarea value={value.about} onChange={e=>p("about",e.target.value)}/></label><Field label="Срок за изработка" value={value.leadDays} onChange={v=>p("leadDays",v)}/><label>Основен цвят<input type="color" value={value.primaryColor} onChange={e=>p("primaryColor",e.target.value)}/></label><Field label="Телефон" value={value.phone} onChange={v=>p("phone",v)}/><Field label="Имейл" value={value.email} onChange={v=>p("email",v)}/><Field label="Facebook линк" value={value.facebook} onChange={v=>p("facebook",v)}/><Field label="Instagram линк" value={value.instagram} onChange={v=>p("instagram",v)}/><Field label="TikTok линк" value={value.tiktok} onChange={v=>p("tiktok",v)}/><label className="wide">Категории <small>разделени със запетая</small><input value={value.categories.join(", ")} onChange={e=>p("categories",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/></label></div></div></div>}
